syntax = "proto3";

package lq;

enum EnErrorCode {
  OK = 0;
  EN_ERR_TIMEOUT = 101;
  EN_ERR_INVALID_PARAM = 102;
  EN_ERR_CANT_AFFORD = 103;
  EN_ERR_NOT_LOGIN = 104;
  EN_ERR_NOT_GM = 105;
  EN_ERR_SYSTEM = 106;
  EN_ERR_USER_NOT_FOUND = 107;
  EN_ERR_REWARD_RECEIVED = 108;
  EN_ERR_NOT_FOUND_UUID = 109;
  EN_ERR_MANUAL_DISCONNECT = 110;
  EN_ERR_LOST_CONNECTION = 111;
  EN_ERR_CONNECT_FAILED = 112;
  EN_ERR_MAINTENANCE = 113;
  EN_ERR_ACCESS_DENY = 114;
  ERR_UNKNOWN = 1;
  ERR_SYSTEM_ERROR = 2;
  ERR_DUPLICATE_SIGN_UP = 1001;
  ERR_NOT_SIGN_UP = 1002;
  ERR_PASSWORD = 1003;
  ERR_NOT_LOGIN = 1004;
  ERR_ALREADY_LOGIN = 1005;
  ERR_ACCOUNT_NOT_EXIST = 1006;
  ERR_ROOM_NOT_EXIST = 1007;
  ERR_ROOM_IS_FULL = 1008;
  ERR_ROOM_ALREADY_LEAVE = 1009;
  ERR_ROOM_NOT_OWNER = 1010;
  ERR_ROOM_NOT_ALL_READY = 1011;
  ERR_TOKEN_NOT_EXIST = 1012;
  ERR_TOKEN_INVALID = 1013;
  ERR_GAME_NOT_EXIST = 1014;
  ERR_GAME_REFUSED = 1015;
  ERR_NOT_PLAYING_GAME = 1016;
}
